FROM entando/entando-java-base:v11.0.4-ENG-5550-PR-18-BB-release-2F-11.0
ARG VERSION
LABEL name="Entando K8S Operator Common" \
      vendor="Entando" \
      version="v${VERSION}" \
      release="7.3" \
      summary="This Docker image contains all the common libraries used by Entando controllers." \
      description="This Docker image contains all the common libraries used by Entando controllers."
COPY target/generated-resources/licenses /licenses
COPY target/quarkus-app/lib /deployments/lib
USER root
RUN chmod ug+rw -R /deployments/ && chown 185:root -R /deployments/
USER 185
ENTRYPOINT [ "/deployments/run-java.sh" ]
